#!/usr/bin/env python3
"""Regenerate C++ tree-gen data from the pinned, vendored Python literals (offline)."""
import ast
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = root / 'vendor/tree-gen'
def assignment(path, name):
    for node in ast.parse(path.read_text()).body:
        if isinstance(node, ast.Assign) and node.targets[0].id == name:
            return ast.literal_eval(node.value)
    raise ValueError(name)
def literal(value):
    if isinstance(value, list):
        return '{' + ', '.join(map(literal, value)) + '}'
    return str(value)
defaults = assignment(source / 'parametric/tree_params/tree_param.py', 'defaults')
header = '// Derived from tree-gen by Charlie Hewitt and Sami Pflibsen-Jones.\n// SPDX-License-Identifier: GPL-3.0-only\n// Generated by tools/import-tree-presets.py; do not edit.\n'
fields = header
for k, v in defaults.items():
    typ = f'std::array<double, {len(v)}>' if isinstance(v, list) else 'double'
    if k in ('shape', 'levels', 'base_splits', 'leaf_shape', 'blossom_shape'):
        typ = 'int'
    fields += f'    {typ} {k} = {literal(v)};\n'
(root / 'src/tree_params.inc').write_text(fields)
presets = header + 'static const std::vector<Preset> presets = {\n'
for path in sorted((source / 'parametric/tree_params').glob('*.py')):
    if path.stem == 'tree_param':
        continue
    values = assignment(path, 'params')
    presets += f'    {{"{path.stem}", [] {{ Parameters p;\n'
    for k, v in values.items():
        if k not in defaults:  # TreeParam ignores legacy keys such as "leaves".
            continue
        presets += f'        p.{k} = {literal(v)};\n'
    presets += '        return p; }()},\n'
presets += '};\n'
(root / 'src/tree_presets.inc').write_text(presets)
# The shape module contains only literal geometry and Vector constructors.
tree = ast.parse((source / 'leaf_shapes.py').read_text())
class Vectors(ast.NodeTransformer):
    def visit_Call(self, node):
        assert isinstance(node.func, ast.Name) and node.func.id == 'Vector'
        return self.visit(node.args[0])
shapes = header + 'static const std::vector<LeafShape> leaf_shapes = {\n'
for func in tree.body:
    if isinstance(func, ast.FunctionDef):
        ret = next(n for n in func.body if isinstance(n, ast.Return))
        values = ast.literal_eval(Vectors().visit(ret.value.value))
        for value in values:
            shapes += '    {' + literal(value[0]) + ', ' + literal(value[1]) + '},\n'
shapes += '};\n'
(root / 'src/tree_shapes.inc').write_text(shapes)

validation = header
for k, v in defaults.items():
    validation += f"    for(auto v:p.{k})finite(v);\n" if isinstance(v,list) else f"    finite(p.{k});\n"
(root / "src/tree_validate.inc").write_text(validation)
